sudo: required
services:
    - docker
    
before_install:
    - docker build -t kaiserskorpion/docker-react -f Dockerfile.dev .
    
script: 
    - docker run kaiserskorpion/docker-react npm run test -- --coverage